"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const mojibakePattern = /[\u93c3\u9359\u95ab\u7490\u93c9\u9422\u95b8\u941c\u6434\u7d31\u6b10\u727d\ufffd]/;

test("frontend visible shell text has no mojibake", () => {
  const files = [
    path.join(root, "public", "finance.html"),
    path.join(root, "public", "app-finance-ui.js"),
  ];
  const offenders = files
    .filter((file) => mojibakePattern.test(fs.readFileSync(file, "utf8")))
    .map((file) => path.relative(root, file));
  assert.deepEqual(offenders, []);
});

test("standalone finance UI keeps mobile navigation and settings", () => {
  const html = fs.readFileSync(path.join(root, "public", "finance.html"), "utf8");
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  assert.match(html, /data-theme="dark"/);
  assert.match(html, /<body class="finance-booting" data-finance-booting="true">/);
  assert.match(html, /user-scalable=no/);
  assert.match(html, /maximum-scale=1/);
  assert.match(html, /class="finance-bottom-nav"/);
  assert.match(html, /<form class="finance-keyboard-composer composer" id="composer" data-hermes-composer data-finance-keyboard-composer>/);
  assert.match(html, /data-refresh aria-label="搜索账单"/);
  assert.match(html, /<textarea id="messageInput" rows="1"[\s\S]*data-finance-keyboard-composer-input><\/textarea>/);
  assert.equal((html.match(/data-nav-view=/g) || []).length, 7);
  for (const label of ["账本", "计划", "记账", "报表", "资产", "股票", "我的"]) assert.match(html, new RegExp(`>${label}<`));
  assert.match(html, /data-nav-view="assets" data-owner-assets-nav hidden/);
  assert.match(html, /data-nav-view="stocks" data-owner-stocks-nav hidden/);
  assert.match(html, /data-view="assets"/);
  assert.match(html, /data-view="stocks"/);
  assert.match(html, /data-asset-summary/);
  assert.match(html, /data-asset-history/);
  assert.match(html, /data-stock-summary/);
  assert.match(html, /data-stock-history/);
  assert.match(js, /selectedOwnerAssetYear/);
  assert.match(js, /selectedOwnerStockDate/);
  assert.match(js, /data-asset-year-list/);
  assert.match(js, /data-asset-year=/);
  assert.match(js, /data-stock-date-list/);
  assert.match(js, /data-stock-date=/);
  assert.match(js, /aria-pressed=/);
  assert.match(js, /Number\(b\.year \|\| 0\) - Number\(a\.year \|\| 0\)/);
  assert.match(js, /人民币总资产/);
  assert.match(js, /美元总资产/);
  assert.match(js, /finance-asset-total-tabs/);
  assert.match(js, /finance-asset-total-tab/);
  assert.match(js, /current_total_assets_usd_minor/);
  assert.match(js, /当前汇率 USD\/CNY/);
  assert.doesNotMatch(js, /USD\/CNY \$\{escapeHtml\(selected\.fx_usd_cny_rate/);
  assert.match(js, /function assetComponentAmount/);
  assert.match(js, /row\.amount_minor/);
  assert.match(js, /scrollIntoView\(\{ block: "nearest", inline: "center" \}\)/);
  assert.match(js, /finance-owner-assets-enabled/);
  assert.match(js, /finance-owner-stocks-enabled/);
  assert.match(js, /function renderOwnerAssets/);
  assert.match(js, /function renderOwnerStocks/);
  assert.match(js, /class="finance-stock-price"/);
  assert.match(js, />当前价格<\/span><strong>\$\{escapeHtml\(stockPositionPrice\(row\)\)\}<\/strong>/);
  assert.doesNotMatch(js, /stockQuantityText\(row\)} · 当前 \$\{stockPositionPrice\(row\)\}/);
  assert.equal(js.includes("owner-stocks/summary?live=1"), true);
  assert.match(js, /data-refresh-owner-assets/);
  assert.match(js, /data-refresh-owner-stocks/);
  assert.match(js, /refreshIconSvg/);
  assert.match(js, /row\.categoryIcon/);
  assert.match(js, /const explicit = String\(input\.icon \|\| input\.categoryIcon \|\| ""\)\.trim\(\)/);
  assert.match(html, /class="finance-nav-primary" data-nav-view="entry"/);
  assert.match(html, /data-settings-overlay/);
  assert.match(html, /data-refresh/);
  assert.match(html, /data-home-currency-button/);
  assert.match(html, /data-open-ledger/);
  assert.match(html, /data-ledger-name/);
  assert.match(html, /data-ledger-overlay/);
  assert.match(html, /class="finance-chip-field finance-currency-field" hidden/);
  assert.match(html, /data-currency-select/);
  assert.match(html, /data-attachment-camera/);
  assert.match(html, /capture="environment"/);
  assert.match(html, /data-attachment-photo/);
  assert.match(html, /data-attachment-file/);
  assert.match(html, /data-attachment-overlay/);
  assert.match(html, /data-category-quick-list/);
  assert.match(html, /class="finance-entry-category-trigger" data-open-category-picker/);
  assert.match(html, /data-category-picker-overlay/);
  assert.match(html, /data-entry-choice-overlay/);
  assert.match(html, /data-open-member-picker/);
  assert.match(html, /data-open-tag-picker/);
  assert.doesNotMatch(html, /merchant-chip/);
  assert.match(html, /data-transaction-search/);
  assert.match(html, /data-transaction-search-status/);
  assert.match(html, /data-summary-label>本年支出/);
  assert.match(html, /class="finance-home-services"/);
  assert.match(html, /class="finance-transaction-services"/);
  assert.match(html, /finance-service-recurring/);
  assert.match(html, /data-switch-view="plan"[\s\S]*周期账/);
  assert.match(html, /data-open-entry-date/);
  assert.match(html, /data-entry-date-button>日期/);
  assert.match(html, /data-entry-date-input/);
  assert.match(html, /type="hidden" name="occurred_at" data-entry-date-input/);
  assert.match(html, /data-open-recurring-create/);
  assert.match(html, /data-generate-recurring-due/);
  assert.match(html, /data-recurring-list/);
  assert.match(html, /data-entry-date-overlay/);
  assert.match(html, /data-recurring-overlay/);
  assert.match(html, /type="hidden" name="note" data-entry-note-value/);
  assert.match(html, /data-open-note-input data-entry-note-label>备注/);
  assert.match(html, /data-entry-note-overlay/);
  assert.doesNotMatch(html, /wacai-entry-note-row/);
  assert.doesNotMatch(html, /data-entry-note-save/);
  assert.match(html, /name="amount" inputmode="none"[\s\S]*readonly[\s\S]*data-entry-amount/);
  assert.match(html, /data-keypad-value="00"/);
  assert.match(html, /data-keypad-value="\."/);
  assert.match(html, /data-keypad-action="equals"/);
  assert.equal(/inputmode="decimal"|inputmode="numeric"/.test(html), false);
  assert.match(js, /fractionCount >= 2/);
  assert.match(js, /Math\.round\(Math\.max\(0, value\) \* 100\) \/ 100/);
  assert.match(js, /function evaluateEntryAmountExpression\(value\)/);
  assert.match(js, /function tokenizeEntryAmountExpression\(value\)/);
  assert.match(js, /function applyEntryAmountOperator\(left, operator, right\)/);
  assert.match(js, /if \(action === "equals"\) \{[\s\S]*computeEntryAmount\(\);[\s\S]*scheduleEntryDraftSave\(\);[\s\S]*return;[\s\S]*\}/);
  assert.doesNotMatch(js, /Function\(`"use strict";return/);
  assert.match(js, /"早餐", "午餐", "晚餐", "夜宵"/);
  assert.match(js, /function preferredMealCategories\(now = new Date\(\)\)/);
  assert.match(js, /hour >= 5 && hour < 10\) return \["早餐", "午餐", "晚餐", "夜宵"\]/);
  assert.match(js, /hour >= 10 && hour < 15\) return \["午餐", "早餐", "晚餐", "夜宵"\]/);
  assert.match(js, /hour >= 15 && hour < 21\) return \["晚餐", "午餐", "夜宵", "早餐"\]/);
  assert.match(js, /return \["夜宵", "晚餐", "早餐", "午餐"\]/);
  assert.match(html, /rel="manifest" href="\/manifest\.json"/);
  assert.match(html, /mobile-web-app-capable/);
  assert.match(html, /data-view="transaction-detail"/);
  assert.match(html, /data-topbar-left/);
  assert.match(html, /Hermes Mobile 只通过 finance MCP/);
  assert.equal(/[\uFFFD]|鏃|璐|鎶|鍟|绫|鍗|鍏|閿|鈱|脳|梅/.test(html), false);
});

test("finance UI consumes host plugin action routes", () => {
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  assert.match(js, /params\.get\("pluginRoute"\)/);
  assert.match(js, /params\.get\("pluginActionId"\)/);
  assert.match(js, /function applyInitialPluginRoute\(\)/);
  assert.match(js, /INITIAL_PLUGIN_ROUTE === "record"/);
  assert.match(js, /INITIAL_PLUGIN_ROUTE === "voice_record"/);
  assert.match(js, /openNewEntry\("expense"\)/);
  assert.match(js, /INITIAL_PLUGIN_ROUTE === "transactions"/);
  assert.match(js, /INITIAL_PLUGIN_ROUTE === "assets"/);
  assert.match(js, /INITIAL_PLUGIN_ROUTE === "budget"/);
  assert.match(js, /INITIAL_PLUGIN_ROUTE === "month_stats"/);
  assert.match(js, /INITIAL_PLUGIN_ROUTE === "year_stats"/);
});

test("finance entry form persists unsaved draft across PWA reloads", () => {
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  assert.match(js, /ENTRY_DRAFT_STORAGE_PREFIX = "finance\.entryDraft\.v1"/);
  assert.match(js, /ENTRY_DRAFT_TTL_MS = 7 \* 24 \* 60 \* 60 \* 1000/);
  assert.match(js, /function currentEntryDraft\(\)/);
  assert.match(js, /amount: normalizeEntryAmount\(selectValue\("\[data-entry-amount\]"\)\)/);
  assert.match(js, /categoryHint: selectValue\("\[data-category-select\]"\)/);
  assert.match(js, /tags: state\.selectedEntryTags\.slice\(0, 20\)/);
  assert.match(js, /function entryDraftAmountHasUserContent\(value\)/);
  assert.match(js, /return \/\[1-9\]\/\.test\(amount\)/);
  assert.match(js, /function restoreEntryDraftOnStartup\(\)/);
  assert.match(js, /async function applyStartupNavigation\(\)/);
  assert.match(js, /if \(restoreEntryDraftOnStartup\(\)\) \{[\s\S]*state\.pluginRouteApplied = true;[\s\S]*return;[\s\S]*\}/);
  assert.match(js, /await applyStartupNavigation\(\)/);
  assert.doesNotMatch(js, /await applyInitialPluginRoute\(\);\s*restoreEntryDraftOnStartup\(\)/);
  assert.match(js, /entryDraftStartupChecked:\s*false/);
  assert.match(js, /if \(state\.entryDraftStartupChecked\) return false;[\s\S]*state\.entryDraftStartupChecked = true/);
  assert.match(js, /openNewEntry\(draft\.mode \|\| draft\.type \|\| "expense", \{ restoreDraft: true \}\)/);
  assert.doesNotMatch(js, /draft\.occurredAt[\s\S]*\|\| draft\.categoryHint[\s\S]*\|\| draft\.memberHint/);
  assert.doesNotMatch(js, /\|\| draft\.accountHint[\s\S]*\|\| draft\.targetAccountHint[\s\S]*\|\| draft\.stayOnEntryAfterSubmit/);
  assert.match(js, /entryDraftRestoredClean:\s*false/);
  assert.match(js, /state\.entryDraftRestoredClean = true;[\s\S]*state\.entryDraftDirty = false/);
  assert.match(js, /function handleEntryDraftPageExit\(\)/);
  assert.match(js, /if \(state\.entryDraftRestoredClean && state\.entryAction === "create"\) \{[\s\S]*clearEntryDraft\(\);[\s\S]*setView\(ROOT_VIEW\);[\s\S]*return;[\s\S]*\}/);
  assert.match(js, /if \(state\.activeView === "entry" && state\.entryAction === "create" && !entryDraftHasUserContent\(draft\)\) \{[\s\S]*clearEntryDraft\(\);[\s\S]*setView\(ROOT_VIEW\);[\s\S]*return;[\s\S]*\}/);
  assert.match(js, /window\.addEventListener\("pagehide", handleEntryDraftPageExit\)/);
  assert.match(js, /document\.visibilityState === "hidden"[\s\S]*handleEntryDraftPageExit\(\)/);
  assert.match(js, /if \(changed\) scheduleEntryDraftSave\(\)/);
  assert.match(js, /clearEntryDraft\(\);[\s\S]*const keepEntry = state\.stayOnEntryAfterSubmit/);
  assert.match(js, /\[data-entry-back\][\s\S]*clearEntryDraft\(\)/);
  assert.match(js, /state\.activeView === "entry"[\s\S]*clearEntryDraft\(\)/);
  assert.doesNotMatch(js, /已恢复未保存草稿/);
});

test("finance CSS follows Wacai replica baseline without disallowed patterns", () => {
  const css = fs.readFileSync(path.join(root, "public", "styles.css"), "utf8");
  assert.equal(/purple|blue-purple|glassmorphism|bokeh|blob/i.test(css), false);
  assert.equal(/font-size\s*:[^;]*(clamp|vw)/.test(css), false);
  assert.match(css, /env\(safe-area-inset-bottom\)/);
  assert.match(css, /html,\s*[\r\n]+body\s*{[\s\S]*overflow-x:\s*hidden/);
  assert.match(css, /\[hidden\]\s*{[\s\S]*display:\s*none !important/);
  assert.match(css, /html\.finance-overlay-open,[\s\S]*body\.finance-overlay-open\s*{[\s\S]*overflow:\s*hidden/);
  assert.match(css, /html\.finance-overlay-open,[\s\S]*body\.finance-overlay-open\s*{[\s\S]*touch-action:\s*none/);
  assert.match(css, /html,\s*[\r\n]+body\s*{[\s\S]*overscroll-behavior-x:\s*none/);
  assert.match(css, /body\s*{[\s\S]*touch-action:\s*pan-y/);
  assert.match(css, /body\.finance-booting \.finance-shell,\s*[\r\n]+body\.finance-booting \.finance-bottom-nav\s*{[\s\S]*visibility:\s*hidden/);
  assert.match(css, /\.finance-keyboard-composer\s*{[\s\S]*width:\s*40px/);
  assert.match(css, /\.finance-keyboard-composer\s*{[\s\S]*height:\s*40px/);
  assert.match(css, /body\.finance-embed \.finance-keyboard-composer\s*{[\s\S]*scroll-margin-bottom:\s*calc\(var\(--finance-keyboard-bottom,\s*0px\) \+ 18px\)/);
  assert.match(css, /\.finance-keyboard-composer textarea\s*{[\s\S]*min-height:\s*40px/);
  assert.match(css, /\.finance-keyboard-composer textarea\s*{[\s\S]*opacity:\s*0\.01/);
  assert.match(css, /\.finance-keyboard-composer textarea\s*{[\s\S]*pointer-events:\s*none/);
  assert.match(css, /body\[data-finance-view="entry"\]\s*{[\s\S]*overflow:\s*hidden/);
  assert.match(css, /html\.finance-entry-open\s*{[\s\S]*overflow:\s*hidden/);
  assert.match(css, /html\.finance-input-focus \.finance-bottom-nav,[\s\S]*html\.finance-input-focus body\.finance-embed::after\s*{[\s\S]*display:\s*none/);
  assert.match(css, /html\.finance-input-focus \.finance-shell\s*{[\s\S]*padding-bottom:\s*calc\(14px \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /html\.finance-input-focus body\.finance-embed \.finance-shell\s*{[\s\S]*padding-bottom:\s*14px/);
  assert.match(css, /\.finance-icon-button\.is-spacer\s*{[\s\S]*visibility:\s*hidden/);
  assert.match(css, /\.finance-shell\s*{[\s\S]*overflow-x:\s*hidden/);
  assert.match(css, /\.finance-view\s*{[\s\S]*overflow-x:\s*hidden/);
  assert.match(css, /\.finance-topbar\s*{[\s\S]*position:\s*fixed/);
  assert.match(css, /--chrome-bg:\s*rgba\(255,\s*255,\s*255,\s*0\.96\)/);
  assert.match(css, /--nav-bg:\s*#ffffff/);
  assert.match(css, /\.finance-topbar\s*{[\s\S]*background:\s*var\(--chrome-bg\)/);
  assert.match(css, /\.finance-topbar \[data-refresh\] \.finance-glyph-refresh::after\s*{[\s\S]*transform:\s*rotate\(45deg\)/);
  assert.match(css, /\.finance-bottom-nav\s*{[\s\S]*background:\s*var\(--nav-bg\)/);
  assert.match(css, /\.finance-bottom-nav\s*{[\s\S]*bottom:\s*calc\(14px \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /\.finance-bottom-nav\s*{[\s\S]*border-radius:\s*24px/);
  assert.match(css, /\.finance-bottom-nav\s*{[\s\S]*grid-template-columns:\s*repeat\(5,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(css, /body\.finance-owner-assets-enabled \.finance-bottom-nav\s*{[\s\S]*grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(css, /\.finance-row\s*{[\s\S]*align-items:\s*start/);
  assert.match(css, /\.finance-row-body\s*{[\s\S]*display:\s*grid[\s\S]*gap:\s*4px/);
  assert.match(css, /\.finance-row-detail\s*{[\s\S]*white-space:\s*nowrap/);
  assert.match(css, /\.finance-row-meta\s*{[\s\S]*white-space:\s*nowrap/);
  assert.match(css, /\.finance-row-amount\s*{[\s\S]*align-self:\s*start/);
  assert.match(css, /\.finance-asset-year-list\s*{[\s\S]*grid-auto-flow:\s*column/);
  assert.match(css, /\.finance-asset-year-list\s*{[\s\S]*overflow-x:\s*auto/);
  assert.match(css, /\.finance-asset-year-list button\.active\s*{[\s\S]*background:\s*#215052/);
  assert.match(css, /\.finance-asset-total-tabs\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/);
  assert.match(css, /\.finance-asset-total-tab\s*{[\s\S]*min-height:\s*118px/);
  assert.match(css, /\.finance-asset-metrics\s*{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(css, /\.finance-asset-live-rate\s*{[\s\S]*font-size:\s*12px/);
  assert.match(css, /\.finance-stock-price\s*{[\s\S]*display:\s*flex/);
  assert.match(css, /\.finance-stock-price strong\s*{[\s\S]*color:\s*var\(--ink\)/);
  assert.match(css, /\.finance-asset-hero\s*{[\s\S]*color:\s*#ffffff/);
  assert.match(css, /\.finance-asset-hero span,[\s\S]*\.finance-asset-hero small\s*{[\s\S]*color:\s*rgba\(255,\s*255,\s*255,\s*0\.78\)/);
  assert.match(css, /\.finance-asset-hero strong\s*{[\s\S]*color:\s*#ffffff/);
  assert.match(css, /\.finance-bottom-nav\s*{[\s\S]*overflow:\s*hidden/);
  assert.match(css, /body\.finance-embed \.finance-shell\s*{[\s\S]*padding-bottom:\s*calc\(var\(--bottom-tabs-bottom\) \+ var\(--bottom-tabs-height\) \+ 18px\)/);
  assert.match(css, /--bottom-tabs-bg:\s*rgba\(29,\s*30,\s*35,\s*0\.92\)/);
  assert.match(css, /--bottom-tabs-bg:\s*rgba\(255,\s*255,\s*255,\s*0\.94\)/);
  assert.match(css, /--bottom-tab-active-border:\s*rgba\(255,\s*255,\s*255,\s*0\.24\)/);
  assert.match(css, /--bottom-tab-active-border:\s*rgba\(20,\s*24,\s*35,\s*0\.34\)/);
  assert.match(css, /body\.finance-embed::after\s*{[\s\S]*display:\s*none/);
  assert.match(css, /:root\[data-theme="dark"\] body\.finance-embed::after\s*{[\s\S]*background:\s*var\(--bottom-tabs-chrome-bg\)/);
  assert.match(css, /:root\[data-theme="light"\] body\.finance-embed::after/);
  assert.match(css, /:root\[data-theme="light"\] body\.finance-embed::after\s*{[\s\S]*background:\s*var\(--bottom-tabs-chrome-bg\)/);
  assert.match(css, /--bottom-tabs-backing-width:\s*min\(522px,\s*calc\(100vw - 70px\)\)/);
  assert.match(css, /body\.finance-embed::after\s*{[\s\S]*left:\s*50%/);
  assert.match(css, /body\.finance-embed::after\s*{[\s\S]*width:\s*var\(--bottom-tabs-backing-width\)/);
  assert.match(css, /body\.finance-embed\[data-finance-view="entry"\]::after,[\s\S]*body\.finance-embed\[data-finance-view="report-detail"\]::after\s*{[\s\S]*display:\s*none/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav\s*{[\s\S]*width:\s*min\(520px,\s*calc\(100vw - 72px\)\)/);
  assert.match(css, /--bottom-tabs-bottom:\s*6px/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav\s*{[\s\S]*bottom:\s*var\(--bottom-tabs-bottom\)/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav\s*{[\s\S]*min-height:\s*var\(--bottom-tabs-height\)/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav\s*{[\s\S]*background:\s*transparent/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav\s*{[\s\S]*border-color:\s*transparent/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav\s*{[\s\S]*box-shadow:\s*none/);
  assert.match(css, /:root\[data-theme="light"\] body\.finance-embed \.finance-bottom-nav/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav button\s*{[\s\S]*min-height:\s*30px/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav button\s*{[\s\S]*background:\s*var\(--bottom-tab-bg\)/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav button\.active\s*{[\s\S]*background:\s*var\(--bottom-tab-active-bg\)/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav button\.active\s*{[\s\S]*border-color:\s*var\(--bottom-tab-active-border\)/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav button\.active\s*{[\s\S]*box-shadow:\s*inset 0 0 0 1px var\(--bottom-tab-active-inset\)/);
  assert.doesNotMatch(css, /data-theme="system"\] body\.finance-embed/);
  assert.match(css, /body\.finance-embed \.finance-bottom-nav \.finance-nav-icon\s*{[\s\S]*display:\s*none/);
  assert.match(css, /body\.finance-embed \.finance-shell\s*{[\s\S]*padding-bottom:\s*calc\(var\(--bottom-tabs-bottom\) \+ var\(--bottom-tabs-height\) \+ 18px\)/);
  assert.match(css, /\.finance-bottom-nav button\s*{[\s\S]*border-radius:\s*14px/);
  assert.match(css, /--wacai-orange:\s*#ff7048/);
  assert.match(css, /--wacai-green:\s*#2fc8b6/);
  assert.match(css, /--entry-bg:\s*#15161a/);
  assert.match(css, /--entry-card:\s*#202126/);
  assert.match(css, /:root\[data-theme="light"\][\s\S]*--entry-bg:\s*#f3f3f6/);
  assert.match(css, /\.wacai-entry-hero/);
  assert.match(css, /wacai-ledger-bg\.svg/);
  assert.match(css, /\.wacai-entry-form\s*{[\s\S]*height:\s*100dvh[\s\S]*overflow:\s*hidden/);
  assert.match(css, /\.finance-entry-category-trigger/);
  assert.match(css, /\.finance-entry-category-current input\s*{[\s\S]*caret-color:\s*transparent/);
  assert.match(css, /\.finance-entry-category-grid\s*{[\s\S]*overflow-y:\s*auto/);
  assert.match(css, /\.finance-entry-category-grid\s*{[\s\S]*touch-action:\s*pan-y/);
  assert.match(css, /\.finance-category-picker-sheet/);
  assert.match(css, /\.finance-category-picker-search/);
  assert.match(css, /\.finance-category-picker-parent/);
  assert.match(css, /\.finance-category-picker-parent\.expanded/);
  assert.match(css, /\.finance-category-picker-grid/);
  assert.match(css, /\.finance-category-picker-item\.active/);
  assert.match(css, /\.finance-category-picker-item \.finance-category-symbol\s*{[\s\S]*width:\s*30px/);
  assert.match(css, /\.finance-category-picker-item \.finance-category-symbol\.svg-icon svg\s*{[\s\S]*width:\s*20px/);
  assert.match(css, /\.finance-transaction-search/);
  assert.match(css, /\.finance-transaction-search-status/);
  assert.match(css, /\.finance-home-services/);
  assert.match(css, /\.finance-transaction-services/);
  assert.match(css, /\.finance-service-recurring/);
  assert.match(css, /\.finance-recurring-toolbar/);
  assert.match(css, /\.finance-recurring-row/);
  assert.match(css, /\.finance-recurring-entry-mode/);
  assert.match(css, /\.finance-recurring-badge/);
  assert.match(css, /--recurring-field-bg:\s*#202126/);
  assert.match(css, /--recurring-field-ink:\s*#f3f4f7/);
  assert.match(css, /--recurring-save-bg:\s*#b83a26/);
  assert.match(css, /:root\[data-theme="light"\][\s\S]*--recurring-field-bg:\s*#ffffff/);
  assert.match(css, /\.finance-recurring-entry-mode\s*{[\s\S]*color-scheme:\s*dark/);
  assert.match(css, /\.finance-recurring-entry-card\s*{[\s\S]*background:\s*var\(--recurring-card-bg\)/);
  assert.match(css, /\.finance-recurring-field\s*{[\s\S]*background:\s*var\(--recurring-field-bg\)/);
  assert.match(css, /\.finance-recurring-field\s*{[\s\S]*border:\s*1px solid var\(--recurring-field-border\)/);
  assert.match(css, /\.finance-recurring-field input,[\s\S]*\.finance-recurring-field select\s*{[\s\S]*color:\s*var\(--recurring-field-ink\)/);
  assert.match(css, /\.finance-recurring-field input,[\s\S]*\.finance-recurring-field select\s*{[\s\S]*color-scheme:\s*dark/);
  assert.match(css, /\.finance-recurring-field input::-webkit-calendar-picker-indicator\s*{[\s\S]*filter:\s*none/);
  assert.match(css, /\.finance-recurring-save\s*{[\s\S]*background:\s*var\(--recurring-save-bg\)/);
  assert.match(css, /:root\[data-theme="light"\] \.finance-recurring-field input,[\s\S]*:root\[data-theme="light"\] \.finance-recurring-field select\s*{[\s\S]*color-scheme:\s*light/);
  assert.match(css, /\.finance-recurring-end-toggle\s*{[\s\S]*background:\s*var\(--recurring-toggle-bg\)/);
  assert.match(css, /\.finance-recurring-form-status/);
  assert.match(css, /\.finance-entry-date-sheet/);
  assert.match(css, /\.finance-overlay\[data-entry-date-variant="wacai"\]\s*{[\s\S]*align-items:\s*end/);
  assert.match(css, /\.finance-entry-date-spacer\s*{[\s\S]*display:\s*none/);
  assert.match(css, /\.finance-date-wheel-card/);
  assert.match(css, /\.finance-date-recurring-pill/);
  assert.match(css, /--entry-date-page-bg:\s*#0f1117/);
  assert.match(css, /--entry-date-card-bg:\s*#1c202b/);
  assert.match(css, /--entry-date-field-bg:\s*#10131b/);
  assert.match(css, /--entry-date-field-ink:\s*#ffffff/);
  assert.match(css, /\.finance-entry-date-fields input\s*{[\s\S]*color-scheme:\s*dark/);
  assert.match(css, /\.finance-entry-date-fields input\s*{[\s\S]*height:\s*46px/);
  assert.match(css, /\.finance-entry-date-fields input\s*{[\s\S]*appearance:\s*none/);
  assert.match(css, /\.finance-entry-date-fields input::-webkit-calendar-picker-indicator\s*{[\s\S]*filter:\s*invert\(1\)/);
});

test("transaction detail view inherits Hermes mobile back behavior", () => {
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  const css = fs.readFileSync(path.join(root, "public", "styles.css"), "utf8");
  assert.match(js, /function goBack\(\)/);
  assert.match(js, /data-transaction-id/);
  assert.match(js, /data-transaction-action="edit"/);
  assert.match(js, /data-transaction-action="copy"/);
  assert.match(js, /data-transaction-action="delete"/);
  assert.match(js, /function openEntryFromTransaction/);
  assert.match(js, /function openTransactionDeleteConfirm/);
  assert.match(js, /function tagNamesText\(row = \{\}\)/);
  assert.match(js, /detailRow\("标签", tagNamesText\(row\)\)/);
  assert.match(js, /function accountOptionLabel\(row\)\s*{[\s\S]*return row\.name;/);
  assert.doesNotMatch(js, /return currency \? `\$\{row\.name\} · \$\{currency\}` : row\.name;/);
  assert.match(js, /function swipeActionButtons\(id\)/);
  assert.match(js, /data-swipe-actions/);
  assert.match(js, /actions\.innerHTML = swipeActionButtons\(row\.dataset\.swipeTransactionId \|\| ""\)/);
  assert.match(js, /if \(actions\) actions\.innerHTML = ""/);
  assert.match(js, /function isIntentionalRowSwipe\(dx, dy\)/);
  assert.match(js, /state\.swipeAxis === "horizontal" && state\.swipeMaxLeft >= 104/);
  assert.match(js, /dx < -88 && dy < 34 && Math\.abs\(dx\) > dy \* 3/);
  assert.match(js, /dy >= 10 && dy >= ax \* 0\.65/);
  assert.match(js, /state\.swipeAxis = "vertical"/);
  assert.match(js, /ax >= 48 && ax > dy \* 2\.8 && dy <= 18/);
  assert.match(js, /state\.swipeAxis = "horizontal"/);
  assert.match(js, /function cancelRowSwipe\(\)/);
  assert.match(js, /state\.swipeAxis = "vertical";[\s\S]*return;/);
  assert.match(js, /swipeHorizontalIntent/);
  assert.match(js, /\/api\/finance\/transactions\/\$\{encodeURIComponent\(row\.id\)\}\/void/);
  assert.match(js, /attachmentCount/);
  assert.match(js, /imageAttachmentCount/);
  assert.match(js, /firstImageUrl/);
  assert.match(js, /function loadTransactionDetailAttachments\(transactionId\)/);
  assert.match(js, /function attachmentThumb\(row = {}\)/);
  assert.match(js, /thumbnailUrl/);
  assert.match(js, /data-attachment-preview-url/);
  assert.match(js, /data-detail-attachment-add/);
  assert.match(js, /function uploadDetailAttachmentFiles\(transactionId, files = \[\]\)/);
  assert.match(js, /method:\s*"PATCH"/);
  assert.match(css, /\.finance-swipe-row/);
  assert.match(css, /\.finance-swipe-row\.actions-open \.finance-row-button\s*{[\s\S]*translateX\(-180px\)/);
  assert.match(css, /\.finance-swipe-actions[\s\S]*grid-template-columns:\s*repeat\(3,\s*1fr\)/);
  assert.match(css, /\.finance-swipe-actions\s*{[\s\S]*visibility:\s*hidden/);
  assert.match(css, /\.finance-swipe-actions\s*{[\s\S]*pointer-events:\s*none/);
  assert.match(css, /\.finance-swipe-row\.actions-open \.finance-swipe-actions\s*{[\s\S]*visibility:\s*visible/);
  assert.match(css, /\.finance-swipe-row\.actions-open \.finance-swipe-actions\s*{[\s\S]*pointer-events:\s*auto/);
  assert.match(css, /\.finance-detail-actions/);
  assert.match(css, /\.finance-row-attachment/);
  assert.match(css, /\.finance-detail-attachments/);
  assert.match(css, /\.finance-detail-attachment-add/);
  assert.match(css, /\.finance-attachment-thumb/);
  assert.match(css, /\.finance-attachment-preview/);
  assert.match(js, /touchstart/);
  assert.match(js, /touchend/);
  assert.match(js, /finance-glyph-back/);
});

test("home transaction list loads 30 rows initially and appends pages at the bottom", () => {
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  const routes = fs.readFileSync(path.join(root, "server-routes", "finance-api-routes.js"), "utf8");
  const repository = fs.readFileSync(path.join(root, "adapters", "finance-repository.js"), "utf8");
  const mcp = fs.readFileSync(path.join(root, "mcp", "finance-tool-contract.js"), "utf8");

  assert.match(js, /const TRANSACTION_PAGE_SIZE = 30/);
  assert.match(js, /const TRANSACTION_LIST_CAP = 200/);
  assert.match(js, /state\.transactionRows = rows\.slice\(\)/);
  assert.match(js, /state\.transactionPageOffset = state\.transactionRows\.length/);
  assert.match(js, /state\.transactionHasMore = rows\.length >= TRANSACTION_PAGE_SIZE/);
  assert.match(js, /function appendTransactionRows\(rows = \[\]\)/);
  assert.match(js, /\/api\/finance\/overview\?\$\{queryString\(\{ limit: TRANSACTION_PAGE_SIZE, summary_only: 1 \}\)\}/);
  assert.match(js, /\/api\/finance\/transactions\?\$\{queryString\(\{[\s\S]*limit: TRANSACTION_PAGE_SIZE,[\s\S]*offset: requestOffset/);
  assert.match(js, /fallbackLimit = Math\.min\(requestOffset \+ TRANSACTION_PAGE_SIZE, TRANSACTION_LIST_CAP\)/);
  assert.match(js, /\/api\/finance\/transactions\?\$\{queryString\(\{ limit: fallbackLimit \}\)\}/);
  assert.match(js, /state\.transactionRows = state\.transactionRows\.concat\(freshRows\)/);
  assert.match(js, /window\.addEventListener\("scroll", \(\) => \{[\s\S]*maybeLoadMoreTransactions\(\);[\s\S]*pinEntryNoteViewportSoon\(0\);[\s\S]*\}, \{ passive: true \}\)/);
  assert.match(js, /window\.addEventListener\("touchend", scheduleTransactionPaginationCheck, \{ passive: true \}\)/);
  assert.match(js, /window\.addEventListener\("wheel", scheduleTransactionPaginationCheck, \{ passive: true \}\)/);
  assert.match(js, /window\.visualViewport\?\.addEventListener\("scroll", \(\) => \{[\s\S]*maybeLoadMoreTransactions\(\)/);
  assert.match(routes, /runtime\.transactionService\.listTransactions\(\{ \.\.\.overviewQuery, limit: overviewQuery\.limit \|\| 30 \}/);
  assert.match(repository, /LIMIT \? OFFSET \?/);
  assert.match(mcp, /offset: \{ type: "integer", minimum: 0, default: 0 \}/);
});

test("report page renders Wacai-like statistics and client auto refresh", () => {
  const html = fs.readFileSync(path.join(root, "public", "finance.html"), "utf8");
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  const css = fs.readFileSync(path.join(root, "public", "styles.css"), "utf8");
  assert.match(html, /data-report-dimension="category"/);
  assert.match(html, /data-report-dimension="subcategory"/);
  assert.match(html, /data-report-dimension="tag"/);
  assert.match(html, /data-report-donut/);
  assert.match(html, /data-report-donut-labels/);
  assert.match(html, /wacai-period-tabs/);
  assert.match(html, /data-report-period="quarter"/);
  assert.match(html, /wacai-date-range/);
  assert.match(html, /data-report-currency-button/);
  assert.match(html, /data-report-prev/);
  assert.match(html, /data-report-next/);
  assert.match(html, /data-report-picker-overlay/);
  assert.match(html, /data-report-action-overlay/);
  assert.match(html, /data-view="report-trend"/);
  assert.match(html, /data-view="report-breakdown"/);
  assert.match(html, /data-view="report-detail"/);
  assert.match(js, /loadReport/);
  assert.match(js, /reportAnchorDate/);
  assert.match(js, /reportAnchorDate:\s*new Date\(\)\.toISOString\(\)/);
  assert.match(js, /function resetReportAnchorToCurrent/);
  assert.match(js, /resetReportAnchorToCurrent\(state\.reportPeriod\)/);
  assert.match(js, /shiftReportPeriod/);
  assert.match(js, /updateReportDateControls/);
  assert.match(js, /activeReportDateParams/);
  assert.match(js, /activeTransactionDateParams/);
  assert.match(js, /function openReportPeriodPicker/);
  assert.match(js, /function openReportDatePicker/);
  assert.match(js, /function renderReportDateWheel/);
  assert.match(js, /function updateReportDateWheel/);
  assert.match(js, /function handleReportWheelScroll/);
  assert.match(js, /function startReportWheelDrag/);
  assert.match(js, /function finishReportWheelDrag/);
  assert.match(js, /function shiftReportWheelValue/);
  assert.match(js, /function applyReportPicker/);
  assert.match(js, /wacai-date-picker-panel/);
  assert.match(js, /wacai-picker-wheel/);
  assert.match(js, /wacai-picker-confirm/);
  assert.match(js, /function refreshOverlayLock/);
  assert.match(js, /data-entry-note-overlay/);
  assert.match(js, /function showOverlay/);
  assert.match(js, /function hideOverlay/);
  assert.match(js, /finance-overlay-open/);
  assert.doesNotMatch(js, /classList\.remove\("hidden"\)/);
  assert.doesNotMatch(js, /classList\.add\("hidden"\)/);
  assert.match(js, /period:\s*state\.reportPeriod/);
  assert.match(js, /startDate:\s*dateToApiStart/);
  assert.match(js, /endDate:\s*dateToApiEnd/);
  assert.match(js, /data-report-picker-period="custom"/);
  assert.match(js, /data-report-picker-period="quarter"/);
  assert.match(js, /type="month"/);
  assert.match(js, /type="date"/);
  assert.match(js, /renderReportRows/);
  assert.match(js, /renderReportRows\(target,\s*items,\s*{\s*interactive:\s*true\s*}\)/);
  assert.doesNotMatch(js, /items\.slice\(0,\s*3\)/);
  assert.doesNotMatch(html, /data-report-expand/);
  assert.match(js, /renderCategoryShortcuts/);
  assert.match(js, /function openCategoryPicker\(\)/);
  assert.match(js, /function closeCategoryPicker\(\)/);
  assert.match(js, /function categoryPickerTree\(categories = \[\]\)/);
  assert.match(js, /function focusCategoryPickerParent\(parentId\)/);
  assert.match(js, /function toggleCategoryPickerParent\(parentId\)/);
  assert.match(js, /function categoryMatchesQuery\(row, query\)/);
  assert.match(js, /function renderCategoryPicker\(options = \{\}\)/);
  assert.match(js, /state\.entryCategories = sortedEntryCategories\(categories\)/);
  assert.match(js, /categoryPickerExpandedParents/);
  assert.match(js, /data-category-picker-parent/);
  assert.match(js, /data-category-picker-search/);
  assert.match(js, /data-category-picker-select/);
  assert.match(js, /data-open-category-picker/);
  assert.match(js, /renderCategoryPicker\(\{ focusParentId: parentId \}\)/);
  assert.match(js, /body\.scrollTop \+= targetTop - bodyTop - 10/);
  assert.match(js, /document\.documentElement\.classList\.toggle\("finance-entry-open", view === "entry"\)/);
  assert.match(js, /\[data-category-picker-overlay\]"\)\?\.addEventListener\("click"/);
  assert.match(js, /function runTransactionSearch\(\)/);
  assert.match(js, /function renderRecurringRules/);
  assert.match(js, /function reportCurrencyRows\(\)/);
  assert.match(js, /function syncReportCurrencyButton\(\)/);
  assert.match(js, /function openReportCurrencyPicker\(event\)/);
  assert.match(js, /async function loadCurrencyOverview\(\)/);
  assert.match(js, /summary_only:\s*1/);
  assert.match(js, /limit:\s*TRANSACTION_PAGE_SIZE/);
  assert.match(js, /renderOverview\(payload\)/);
  assert.match(js, /async function loadOverview\(\)[\s\S]*summary_only:\s*1/);
  assert.match(js, /startupRevealPending:\s*true/);
  assert.match(js, /function revealStartupShell\(\)/);
  assert.match(js, /document\.body\.classList\.remove\("finance-booting"\)/);
  assert.match(js, /document\.body\.removeAttribute\("data-finance-booting"\)/);
  assert.match(js, /renderOverview\(payload\);[\s\S]*await applyStartupNavigation\(\);[\s\S]*revealStartupShell\(\);/);
  assert.match(js, /loadOverview\(\)\.catch\(\(err\) => \{[\s\S]*revealStartupShell\(\);[\s\S]*showError\(err\);[\s\S]*\}\)/);
  assert.doesNotMatch(js, /async function loadOverview\(\)[\s\S]*queryString\(\{ limit: TRANSACTION_PAGE_SIZE, currency: state\.reportCurrency \}\)/);
  assert.match(js, /if \(view === "assets"\) refreshOwnerAssetsLive\(\)/);
  assert.match(js, /async function refreshOwnerAssetsLive\(\)/);
  assert.match(js, /\/api\/finance\/owner-assets\/summary\?refresh_live_fx=1/);
  assert.match(js, /async function applyReportCurrency\(code\)/);
  assert.match(js, /await loadCurrencyOverview\(\)/);
  assert.doesNotMatch(js, /async function applyReportCurrency\(code\)[\s\S]*?await loadOverview\(\);[\s\S]*?if \(state\.activeView === "reports"\)/);
  assert.match(js, /const homeSummary = data\.yearSummary \|\| data\.summary/);
  assert.match(js, /summaryLabel\.textContent = homeSummary === data\.yearSummary \? "本年支出" : "本月支出"/);
  assert.match(js, /function entryRecurringDraft/);
  assert.match(js, /function openEntryDatePicker/);
  assert.match(js, /function applyEntryDatePicker/);
  assert.match(js, /function openRecurringEditor/);
  assert.match(js, /function submitRecurringForm/);
  assert.match(js, /function setRecurringFormStatus/);
  assert.match(js, /function syncRecurringEndMode/);
  assert.match(js, /\/api\/finance\/recurring-rules/);
  assert.match(js, /data-recurring-toggle/);
  assert.match(js, /data-recurring-delete/);
  assert.match(js, /data-recurring-end-mode="forever"/);
  assert.match(js, /data-recurring-form-status/);
  assert.match(js, /data-open-entry-date/);
  assert.match(js, /data-entry-date-step/);
  assert.match(js, /data-date-save-recurring/);
  assert.match(js, /function openEntryNoteOverlay\(\)/);
  assert.match(js, /function applyEntryNoteOverlay\(\)/);
  assert.match(js, /function setEntryNote\(value = ""\)/);
  assert.match(js, /data-entry-note-editor/);
  assert.match(js, /data-open-note-input/);
  assert.match(js, /overlay\?\.contains\(document\.activeElement\)[\s\S]*document\.activeElement\.blur\(\)/);
  assert.match(js, /window\.setTimeout\(refreshInputFocusState, 0\)/);
  assert.match(js, /function scheduleTransactionSearch\(value\)/);
  assert.match(js, /function openBillSearch\(\)/);
  assert.match(js, /function submitKeyboardComposerSearch\(input\)/);
  assert.match(js, /state\.transactionSearchQuery = value;[\s\S]*setView\("transactions"\);[\s\S]*commitTransactionSearch\(search\)/);
  assert.match(js, /function focusTransactionSearchInput\(\)/);
  assert.match(js, /focusTransactionSearchInput\(\);\s*window\.setTimeout\(focusTransactionSearchInput, 60\);\s*window\.setTimeout\(focusTransactionSearchInput, 180\)/);
  assert.match(js, /function refreshInputFocusState\(\)/);
  assert.match(js, /document\.documentElement\.classList\.toggle\("finance-input-focus", focused \|\| noteFocused\)/);
  assert.match(js, /const noteFocused = Boolean\(active && active\.matches\?\.\("\[data-entry-note-editor\]"\)\) \|\| entryNoteOverlayActive\(\)/);
  assert.match(js, /document\.documentElement\.classList\.toggle\("finance-entry-note-focus", noteFocused\)/);
  assert.match(js, /keyboardComposerInput\?\.addEventListener\("search", \(event\) => submitKeyboardComposerSearch\(event\.currentTarget\)\)/);
  assert.match(js, /document\.documentElement\.classList\.toggle\("keyboard-open", viewport\.keyboardShrunk\)/);
  assert.match(js, /function updateKeyboardViewportOffset\(options = \{\}\)/);
  assert.match(js, /viewport: "hermes\.plugin\.viewport"/);
  assert.match(js, /hermesHostViewport:\s*null/);
  assert.match(js, /data\.type === HERMES_EVENTS\.viewport/);
  assert.match(js, /data\.pluginId && data\.pluginId !== "finance"/);
  assert.match(js, /state\.hermesHostViewport = Object\.assign\(\{\}, data, \{ receivedAt: Date\.now\(\) \}\)/);
  assert.match(js, /if \(!entryNoteOverlayActive\(\)\) updateKeyboardViewportOffset\(\)/);
  assert.match(js, /scheduleUiProbe\("hermes-host-viewport"\)/);
  assert.match(js, /function handleHermesPluginViewportMessage\(data = \{\}\)/);
  assert.match(js, /window\.handleHermesPluginViewportMessage = handleHermesPluginViewportMessage/);
  assert.match(js, /if \(handleHermesPluginViewportMessage\(data\)\) return/);
  assert.match(js, /function entryNoteOverlayActive\(\)/);
  assert.match(js, /overlay\.dataset\.entryNoteActive === "true"/);
  assert.match(js, /function financeViewportState\(\)/);
  assert.match(js, /const localScrollTop = Math\.max\(/);
  assert.match(js, /const localVisibleTop = Math\.max\(visualOffsetTop, localScrollTop\)/);
  assert.match(js, /const keyboardEditable = Boolean\(active && active\.matches\?\.\("input:not\(\[type='hidden'\]\):not\(\[readonly\]\), textarea, \[contenteditable='true'\]"\)\) \|\| entryNoteOverlayActive\(\)/);
  assert.match(js, /const offsetKeyboardShrunk = Boolean\(keyboardEditable && visualOffsetTop > 40\)/);
  assert.match(js, /const scrollKeyboardShifted = Boolean\(keyboardEditable && localScrollTop > 40\)/);
  assert.match(js, /const effectiveTop = keyboardShrunk \? Math\.max\(0, Math\.round\(localVisibleTop \|\| 0\)\) : 0/);
  assert.match(js, /top:\s*effectiveTop/);
  assert.match(js, /keyboardBottom,\s*\n\s*keyboardShrunk/);
  assert.doesNotMatch(js, /embeddedHostViewportState\(layout\)/);
  assert.match(js, /function updateFinanceViewportVars\(\)/);
  assert.match(js, /--finance-app-top/);
  assert.match(js, /--finance-app-height/);
  assert.match(js, /--app-top/);
  assert.match(js, /--app-height/);
  assert.match(js, /visualOffsetTop/);
  assert.match(js, /finance-keyboard-open/);
  assert.match(js, /viewport\.keyboardShrunk \|\| IS_HERMES_EMBED/);
  assert.match(js, /--finance-keyboard-bottom/);
  assert.match(js, /--finance-visual-bottom/);
  assert.match(js, /--finance-note-bottom-edge/);
  assert.match(js, /finance-native-keyboard-visible/);
  assert.match(js, /if \(!noteFocused\)[\s\S]*--finance-keyboard-bottom", "0px"/);
  assert.match(js, /if \(!noteFocused\)[\s\S]*--finance-visual-bottom", `\$\{viewport\.visualBottom \|\| Math\.round\(window\.innerHeight\)\}px`/);
  assert.match(js, /if \(!noteFocused\)[\s\S]*--finance-note-bottom-edge", `\$\{viewport\.visualBottom \|\| Math\.round\(window\.innerHeight\)\}px`/);
  assert.match(js, /function noteBottomEdgeFromViewport\(visualBottom, keyboard\)/);
  assert.match(js, /function syncEntryNoteSheetMetrics\(\)/);
  assert.match(js, /function resetEntryNoteScrollPosition\(\)/);
  assert.match(js, /Boolean\(active && active\.matches\?\.\("\[data-entry-note-editor\]"\)\) \|\| entryNoteOverlayActive\(\)/);
  assert.match(js, /window\.scrollTo\(0, 0\)/);
  assert.match(js, /function pinEntryNoteViewport\(\)/);
  assert.match(js, /function pinEntryNoteViewportSoon\(delay = 0\)/);
  assert.match(js, /function scheduleEntryNoteViewportPinning\(\)/);
  assert.match(js, /\[0, 50, 120, 220, 360, 560, 840, 1200, 1800, 2600, 3600\]\.forEach/);
  assert.match(js, /window\.addEventListener\("scroll", \(\) => \{[\s\S]*pinEntryNoteViewportSoon\(0\)/);
  assert.match(js, /window\.visualViewport\?\.addEventListener\("resize", \(\) => \{[\s\S]*pinEntryNoteViewportSoon\(0\)/);
  assert.match(js, /window\.visualViewport\?\.addEventListener\("scroll", \(\) => \{[\s\S]*pinEntryNoteViewportSoon\(0\)/);
  assert.match(js, /--finance-note-sheet-height/);
  assert.match(js, /const cappedKeyboard = Math\.min\(Math\.round\(keyboard\), Math\.round\(layoutHeight \* 0\.42\)\)/);
  assert.match(js, /const readableFloor = Math\.round\(layoutHeight \* 0\.58\)/);
  assert.match(js, /copyAmountPristine:\s*false/);
  assert.match(js, /state\.copyAmountPristine = action === "copy"/);
  assert.match(js, /function consumeCopyAmountIfNeeded\(token = ""\)/);
  assert.match(js, /if \(!\/\^\[\\d\.\]\$\/\.test\(String\(token \|\| ""\)\) && token !== "00"\)/);
  assert.match(js, /function preventAmountNativeKeyboard\(event\)/);
  assert.match(js, /\[data-entry-amount\]"\)\?\.addEventListener\("pointerdown", preventAmountNativeKeyboard\)/);
  assert.match(js, /\[data-entry-amount\]"\)\?\.addEventListener\("touchstart", preventAmountNativeKeyboard, \{ passive: false \}\)/);
  assert.match(js, /function openEntryChoicePicker\(kind = "member"\)/);
  assert.match(js, /function applyEntryChoiceValue\(value, button = null\)/);
  assert.match(js, /state\.selectedEntryTags/);
  assert.match(js, /tags:\s*state\.selectedEntryTags/);
  assert.match(js, /if \(action === "copy"\)[\s\S]*setEntryDateValue\(dateInputText\(now\)/);
  assert.match(js, /button\.hidden = false/);
  assert.match(js, /button\.classList\.toggle\("is-spacer", !secondary\)/);
  assert.match(js, /button\.addEventListener\("click", openBillSearch\)/);
  assert.match(js, /search: query/);
  assert.match(js, /state\.transactionSearchRows\.find/);
  assert.match(html, /enterkeyhint="search"[^>]*data-transaction-search/);
  assert.match(js, /const transactionSearchInput = \$\("\[data-transaction-search\]"\)/);
  assert.match(js, /transactionSearchInput\?\.addEventListener\("input"/);
  assert.match(js, /function commitTransactionSearch/);
  assert.match(js, /transactionSearchInput\?\.addEventListener\("search", \(event\) => commitTransactionSearch\(event\.currentTarget\)\)/);
  assert.match(js, /transactionSearchInput\?\.addEventListener\("keydown"/);
  assert.match(js, /if \(event\.key !== "Enter"\) return/);
  assert.match(js, /input\.blur\(\)/);
  assert.match(js, /window\.setTimeout\(refreshInputFocusState, 0\)/);
  assert.match(js, /可左滑复制/);
  assert.match(js, /CATEGORY_ICON_KEYS/);
  assert.match(js, /"家政服务", "home-service"/);
  assert.match(js, /"税费手续费", "tax-fee"/);
  assert.match(js, /"物业", "property"/);
  assert.match(js, /"电费", "utility-power"/);
  assert.match(js, /"牙科", "medical-dental"/);
  assert.match(js, /"medical-dental":/);
  assert.match(js, /"home-service":/);
  assert.match(js, /"tax-fee":/);
  assert.match(js, /data-category-quick/);
  assert.match(js, /openReportActions/);
  assert.match(js, /openReportTrend/);
  assert.match(js, /openReportDetail/);
  assert.match(js, /data-report-breakdown-index/);
  assert.match(js, /checkClientVersion/);
  assert.match(js, /client-version/);
  assert.match(js, /pendingClientVersion/);
  assert.match(js, /function requestClientReload\(version\)/);
  assert.match(js, /function applyPendingClientReload\(\)/);
  assert.match(js, /if \(state\.activeView !== ROOT_VIEW \|\| currentCanGoBack\(\)\) return/);
  assert.match(js, /window\.location\.reload/);
  assert.match(js, /serviceWorker/);
  assert.match(js, /service-worker\.js/);
  assert.match(js, /formatWacaiDate/);
  assert.match(js, /formatWacaiTime/);
  assert.match(js, /function formatTransactionRowDateTime\(value\)/);
  assert.match(js, /\$\{date\.getFullYear\(\)\}\/\$\{pad2\(date\.getMonth\(\) \+ 1\)\}\/\$\{pad2\(date\.getDate\(\)\)\} \$\{formatWacaiTime\(value\)\}/);
  assert.match(js, /const detailLine = \[row\.note, row\.merchantName\]\.filter\(Boolean\)\.join\(" · "\)/);
  assert.match(js, /const dateLine = \[formatTransactionRowDateTime\(row\.occurredAt\), row\.accountName, row\.memberName\]\.filter\(Boolean\)\.join\(" · "\)/);
  assert.match(js, /class="finance-row-body"/);
  assert.match(js, /class="finance-row-detail"/);
  assert.doesNotMatch(js, /\[row\.note, formatWacaiTime\(row\.occurredAt\), row\.accountName/);
  assert.doesNotMatch(js, /\[row\.note, formatTransactionRowDateTime\(row\.occurredAt\), row\.accountName/);
  assert.match(js, /currencyLabel/);
  assert.match(js, /function sortedAccounts/);
  assert.match(js, /function accountOptions/);
  assert.match(js, /accountOptionLabel/);
  assert.match(js, /data-currency="\$\{escapeHtml\(row\.currency \|\| "CNY"\)\}"/);
  assert.match(js, /function syncEntryCurrencyFromAccount\(\)/);
  assert.match(js, /financeActiveLedgerId/);
  assert.match(js, /function withActiveLedger\(path\)/);
  assert.match(js, /url\.searchParams\.set\("ledger_id", state\.activeLedgerId\)/);
  assert.match(js, /function renderLedgerMenu\(\)/);
  assert.match(js, /data-ledger-select/);
  assert.match(js, /data-ledger-create-form/);
  assert.match(js, /\/api\/finance\/ledgers/);
  assert.match(js, /function categoryUsageCount\(row\)/);
  assert.match(js, /state\.overview\?\.categoryUsage/);
  assert.match(js, /const usageDiff = categoryUsageCount\(b\) - categoryUsageCount\(a\)/);
  assert.match(js, /function openAttachmentMenu\(transactionId = ""\)/);
  assert.match(js, /data-attachment-action="camera"/);
  assert.match(js, /data-attachment-action="photo"/);
  assert.match(js, /data-attachment-action="file"/);
  assert.match(js, /function uploadAttachmentFiles\(transactionId, files = \[\]\)/);
  assert.match(js, /function uploadPendingAttachments\(transactionId\)/);
  assert.match(js, /function handleAttachmentFiles\(files = \[\]\)/);
  assert.match(js, /openAttachmentMenu\(detailAttachmentAdd\.dataset\.detailAttachmentAdd\)/);
  assert.match(js, /closeAttachmentMenu\(\{ preserveTarget: true \}\)/);
  assert.match(js, /\/api\/finance\/attachments/);
  assert.match(js, /readAsDataURL/);
  assert.match(js, /\[data-attachment-camera\]"\)\?\.addEventListener\("change", \(event\) => handleAttachmentFiles/);
  assert.match(js, /\[data-account-select\]"\)\?\.addEventListener\("change", \(\) => \{[\s\S]*?syncEntryCurrencyFromAccount\(\);[\s\S]*?scheduleEntryDraftSave\(\);/);
  assert.match(js, /\[data-member-select\]"\)\?\.addEventListener\("change", \(\) => \{[\s\S]*?syncEntryMemberLabel\(\);[\s\S]*?scheduleEntryDraftSave\(\);/);
  assert.match(js, /finance-account-group/);
  assert.match(js, /reportCurrency:\s*"CNY"/);
  assert.match(js, /function reportUsesOriginalCurrency/);
  assert.match(js, /!currency && \(dimension === "account"/);
  assert.match(js, /filters\.account_id \|\| filters\.accountId/);
  assert.match(js, /params\.currency = state\.reportCurrency/);
  assert.match(js, /detailQuery\.currency = state\.reportCurrency/);
  assert.match(js, /currency:\s*state\.reportCurrency/);
  assert.match(js, /\[data-report-currency-button\]/);
  assert.match(js, /\[data-home-currency-button\]/);
  assert.match(js, /function openReportCurrencyPicker\(event\)/);
  assert.match(js, /event\?\.stopPropagation\?\.\(\);[\s\S]*const overlay = \$\("\[data-report-picker-overlay\]"\)/);
  assert.match(js, /const currency = event\.target\.closest\("\[data-report-picker-currency\]"\);[\s\S]*event\.stopPropagation\(\);[\s\S]*applyReportCurrency/);
  assert.match(js, /formatMoney/);
  assert.match(js, /formatMinorMoney/);
  assert.match(js, /function groupMoneyWholeDigits\(value = "0"\)/);
  assert.match(js, /function formatMoney\(value, options = \{\}\)/);
  assert.match(js, /function formatMinorMoney\(value, scale = 2\)/);
  assert.match(js, /function displayMoneyAmount\(row = \{\}, fallback = ""\)/);
  assert.match(js, /function displayAbsoluteMoneyAmount\(row = \{\}, fallback = "0"\)/);
  assert.match(js, /fractionMinor === 0n/);
  assert.match(js, /return `\$\{sign\}\$\{displayAbsoluteMoneyAmount\(row, "0"\)\}\$\{suffix\}`/);
  assert.match(js, /const amount = displayMoneyAmount\(item, amountFallback \? "0" : ""\)/);
  assert.match(js, /displayMoneyAmount\(item, "0"\)/);
  assert.match(js, /return displayAbsoluteMoneyAmount\(row, "0"\)\.replaceAll\(",", ""\)/);
  assert.doesNotMatch(js, /Math\.round\(numeric\)\.toLocaleString\("zh-CN", \{ maximumFractionDigits: 0 \}\)/);
  assert.doesNotMatch(js, /Math\.round\(amountMinor \/ 100\)/);
  assert.match(js, /function formatComputedEntryAmount\(value\)/);
  assert.match(css, /conic-gradient/);
  assert.match(css, /\.finance-date-header/);
  assert.match(css, /\.finance-action-sheet/);
  assert.match(css, /\.finance-entry-category-grid/);
  assert.match(css, /\.finance-category-chip/);
  assert.match(css, /\.wacai-keypad/);
  assert.match(css, /--entry-keypad-side-gutter:\s*max\(20px,\s*env\(safe-area-inset-left\)\)/);
  assert.match(css, /--entry-keypad-end-gutter:\s*max\(12px,\s*env\(safe-area-inset-right\)\)/);
  assert.match(css, /\.wacai-keypad\s*{[\s\S]*box-sizing:\s*border-box/);
  assert.match(css, /\.wacai-keypad\s*{[\s\S]*padding:\s*0 var\(--entry-keypad-end-gutter\) env\(safe-area-inset-bottom\) var\(--entry-keypad-side-gutter\)/);
  assert.match(css, /\.wacai-keypad\s*{[\s\S]*user-select:\s*none/);
  assert.match(css, /\.wacai-keypad button\.active/);
  assert.match(js, /function setStayOnEntryAfterSubmit\(value = false\)/);
  assert.match(js, /if \(action === "again"\) \{[\s\S]*setStayOnEntryAfterSubmit\(!state\.stayOnEntryAfterSubmit\);[\s\S]*return;/);
  assert.doesNotMatch(js, /if \(action === "again"\) \{[\s\S]*requestSubmit\(\)/);
  assert.match(css, /\.finance-entry-note-sheet\s*{[\s\S]*padding:\s*0 14px calc\(14px \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /body\.finance-embed\s*{[\s\S]*min-height:\s*100%/);
  assert.match(css, /body\.finance-embed \.finance-shell\s*{[\s\S]*min-height:\s*100%/);
  assert.match(css, /html\.finance-entry-note-focus \.finance-overlay\[data-entry-note-active="true"\]\s*{[\s\S]*top:\s*var\(--finance-app-top,\s*0px\)/);
  assert.match(css, /html\.finance-entry-note-focus \.finance-overlay\[data-entry-note-active="true"\]\s*{[\s\S]*position:\s*absolute/);
  assert.match(css, /html\.finance-entry-note-focus \.finance-overlay\[data-entry-note-active="true"\]\s*{[\s\S]*height:\s*var\(--finance-app-height,\s*100dvh\)/);
  assert.match(css, /html\.finance-entry-note-focus,\s*html\.finance-entry-note-focus body\s*{[\s\S]*overflow:\s*hidden/);
  assert.match(css, /html\.finance-entry-note-focus body\.finance-embed\s*{[\s\S]*position:\s*relative/);
  assert.match(css, /html\.finance-entry-note-focus body\.finance-embed \.finance-overlay\[data-entry-note-active="true"\]\s*{[\s\S]*height:\s*var\(--finance-app-height,\s*100%\)/);
  assert.match(css, /html\.finance-entry-note-focus \.finance-overlay\[data-entry-note-active="true"\]\s*{[\s\S]*align-items:\s*end/);
  assert.match(css, /html\.finance-entry-note-focus \.finance-overlay\[data-entry-note-active="true"\] \.finance-entry-note-sheet\s*{[\s\S]*position:\s*relative/);
  assert.match(css, /html\.finance-entry-note-focus \.finance-overlay\[data-entry-note-active="true"\] \.finance-entry-note-sheet\s*{[\s\S]*width:\s*min\(100%,\s*560px\)/);
  assert.match(css, /\.finance-entry-note-header\s*{[\s\S]*grid-template-columns:\s*64px minmax\(0,\s*1fr\) 64px/);
  assert.match(css, /\.finance-entry-note-header \[data-entry-note-apply\]\s*{[\s\S]*color:\s*var\(--wacai-orange\)/);
  assert.match(css, /\.finance-entry-note-sheet textarea\s*{[\s\S]*min-height:\s*116px/);
  assert.match(css, /\.finance-entry-note-sheet textarea\s*{[\s\S]*touch-action:\s*pan-y/);
  assert.doesNotMatch(css, /wacai-entry-note-row/);
  assert.doesNotMatch(css, /wacai-note-save/);
  assert.match(css, /\.finance-entry-choice-sheet/);
  assert.match(css, /\.finance-entry-choice-row\.active b/);
  assert.match(css, /\.wacai-entry-meta\s*{[\s\S]*align-items:\s*center/);
  assert.match(css, /\.wacai-entry-meta\s*{[\s\S]*flex-wrap:\s*nowrap/);
  assert.match(css, /\.wacai-entry-meta\s*{[\s\S]*overflow-y:\s*hidden/);
  assert.match(css, /\.wacai-entry-meta\s*{[\s\S]*touch-action:\s*pan-x/);
  assert.match(css, /\.wacai-entry-meta\s*{[\s\S]*padding:\s*0 60px 8px 8px/);
  assert.match(css, /\.wacai-camera-button\s*{[\s\S]*position:\s*absolute/);
  assert.match(css, /\.wacai-camera-button\s*{[\s\S]*right:\s*10px/);
  assert.match(css, /\.finance-chip-field input,[\s\S]*\.wacai-meta-button\s*{[\s\S]*height:\s*32px/);
  assert.match(css, /body\[data-finance-view="reports"\] \.finance-topbar\s*{[\s\S]*display:\s*none/);
  assert.match(css, /body\[data-finance-view="reports"\] \.finance-shell\s*{[\s\S]*padding-top:\s*0/);
  assert.match(css, /\.finance-report-filter-top\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) 92px/);
  assert.match(css, /\.wacai-period-tabs\s*{[\s\S]*width:\s*100%/);
  assert.match(css, /\.finance-report-currency-button\s*{[\s\S]*min-height:\s*42px/);
  assert.match(css, /\.finance-view\[data-view="home"\]\.active\s*{[\s\S]*gap:\s*10px/);
  assert.match(css, /\.finance-summary\s*{[\s\S]*grid-template-areas:[\s\S]*"label amount currency"/);
  assert.match(css, /\.finance-summary\s*{[\s\S]*padding:\s*10px 12px 9px/);
  assert.match(css, /\.finance-summary-top\s*{[\s\S]*display:\s*contents/);
  assert.match(css, /\.finance-summary-currency-button\s*{[\s\S]*min-height:\s*28px/);
  assert.match(css, /\.finance-summary-amount\s*{[\s\S]*font-size:\s*27px/);
  assert.match(css, /\.finance-summary-row\s*{[\s\S]*margin-top:\s*0/);
  assert.match(css, /\.finance-home-services button\s*{[\s\S]*min-height:\s*56px/);
  assert.match(css, /\.finance-home-services button\s*{[\s\S]*gap:\s*4px/);
  assert.match(css, /\.finance-home-services \.finance-service-icon\s*{[\s\S]*width:\s*32px/);
  assert.match(css, /\.finance-summary-currency-button::after,[\s\S]*\.finance-report-currency-button::after/);
  assert.match(css, /\.wacai-report-filter\s*{[\s\S]*overflow:\s*hidden/);
  assert.match(css, /\.wacai-date-range\s*{[\s\S]*display:\s*grid/);
  assert.match(css, /\.wacai-date-range\s*{[\s\S]*grid-template-columns:\s*32px minmax\(0,\s*1fr\) 18px minmax\(0,\s*1fr\) 32px 38px/);
  assert.match(css, /\.wacai-date-range \[data-report-date-start\]\s*{[\s\S]*grid-column:\s*2/);
  assert.match(css, /\.wacai-date-range \.wacai-filter-button\s*{[\s\S]*grid-column:\s*6/);
  assert.match(css, /\.wacai-date-range \[data-report-prev\],[\s\S]*\.wacai-date-range \[data-report-next\]\s*{[\s\S]*width:\s*32px/);
  assert.match(css, /\.wacai-date-range button:not\(\.wacai-filter-button\):not\(\[data-report-prev\]\):not\(\[data-report-next\]\)::after/);
  assert.match(css, /\.finance-report-tabs\s*{[\s\S]*overscroll-behavior-x:\s*contain/);
  assert.match(css, /\.finance-report-tabs\s*{[\s\S]*touch-action:\s*pan-x/);
  assert.match(css, /\.finance-report-picker-sheet/);
  assert.match(css, /\.finance-overlay\s*{[\s\S]*touch-action:\s*none/);
  assert.match(css, /\.finance-overlay\s*{[\s\S]*z-index:\s*60/);
  assert.match(css, /html\.finance-overlay-open \.finance-bottom-nav,[\s\S]*body\.finance-overlay-open \.finance-bottom-nav\s*{[\s\S]*pointer-events:\s*none/);
  assert.match(css, /\.finance-overlay\s*{[\s\S]*overscroll-behavior:\s*contain/);
  assert.match(css, /\.finance-report-picker-sheet\s*{[\s\S]*overflow:\s*auto/);
  assert.match(css, /\.finance-report-picker-sheet\s*{[\s\S]*touch-action:\s*pan-y/);
  assert.match(css, /\.finance-report-picker-presets/);
  assert.match(css, /\.finance-report-picker-fields/);
  assert.match(css, /\.finance-report-currency-list/);
  assert.match(css, /\.finance-overlay\[data-report-picker-variant="date-wheel"\]\s*{[\s\S]*align-items:\s*start/);
  assert.match(css, /\.wacai-date-picker-panel/);
  assert.match(css, /\.wacai-picker-period-tabs/);
  assert.match(css, /\.wacai-picker-date-row/);
  assert.match(css, /\.wacai-picker-wheel::before/);
  assert.match(css, /\.wacai-picker-column button\.selected/);
  assert.match(css, /\.wacai-picker-column\s*{[\s\S]*touch-action:\s*none/);
  assert.match(css, /\.wacai-picker-column button\s*{[\s\S]*touch-action:\s*none/);
  assert.match(css, /\.wacai-picker-confirm/);
  assert.match(css, /\.finance-action-sheet,[\s\S]*\.finance-settings-sheet\s*{[\s\S]*overflow:\s*auto/);
  assert.match(css, /\.finance-trend-chart/);
  assert.match(css, /\.finance-report-row/);
  assert.match(css, /\.finance-account-group/);
  assert.match(css, /\.finance-account-group-title/);
  assert.match(css, /\.finance-category-symbol/);
  assert.equal(/finance-donut-small/.test(html + css), false);
});

test("finance UI reports real PWA layout probes for Harness validation", () => {
  const html = fs.readFileSync(path.join(root, "public", "finance.html"), "utf8");
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  const serviceWorker = fs.readFileSync(path.join(root, "public", "service-worker.js"), "utf8");
  const captureHarness = fs.readFileSync(path.join(root, "scripts", "capture-desktop-pwa.js"), "utf8");

  assert.match(html, /styles\.css\?v=finance-replica-20260620d/);
  assert.match(html, /app-finance-ui\.js\?v=finance-replica-20260620d/);
  assert.doesNotMatch(html, /<h2>最近明细<\/h2>/);
  assert.doesNotMatch(html, /<header class="finance-section-header">\s*<h2>最近明细<\/h2>\s*<button type="button" data-switch-view="transactions">全部<\/button>/);
  assert.match(serviceWorker, /finance-mcp-pwa-v148/);
  assert.match(serviceWorker, /url\.pathname\.startsWith\("\/api\/"\)/);
  assert.match(js, /function collectUiProbe/);
  assert.match(js, /function roundRectValue\(value\)/);
  assert.match(js, /function postUiProbe/);
  assert.match(js, /function scheduleUiProbe/);
  assert.match(js, /__financePostUiProbe/);
  assert.match(js, /\/api\/finance\/ui-probe/);
  assert.match(js, /navigator\.sendBeacon/);
  assert.match(js, /visualViewport/);
  assert.match(js, /display-mode: standalone/);
  assert.match(js, /safe-area-inset-top/);
  assert.match(js, /const VISUAL_PROBE = params\.get\("finance_ui_probe"\) \|\| ""/);
  assert.match(js, /const VISUAL_PROBE_KEYBOARD_BOTTOM = Math\.max\(0, Math\.min\(640/);
  assert.match(js, /function forceEntryNoteVisualProbe/);
  assert.match(js, /function applyVisualProbeIfRequested/);
  assert.match(js, /applyVisualProbeIfRequested\(\)/);
  assert.match(js, /focus:\s*{/);
  assert.match(js, /entryNoteFocus:\s*document\.documentElement\.classList\.contains\("finance-entry-note-focus"\)/);
  assert.match(js, /nativeKeyboardVisible:\s*document\.documentElement\.classList\.contains\("finance-native-keyboard-visible"\)/);
  assert.match(js, /appHeightStyle:\s*getComputedStyle\(document\.documentElement\)\.getPropertyValue\("--app-height"\)/);
  assert.match(js, /appTop:\s*getComputedStyle\(document\.documentElement\)\.getPropertyValue\("--finance-app-top"\)/);
  assert.match(js, /keyboardBottom:\s*getComputedStyle\(document\.documentElement\)\.getPropertyValue\("--finance-keyboard-bottom"\)/);
  assert.match(js, /visualBottom:\s*getComputedStyle\(document\.documentElement\)\.getPropertyValue\("--finance-visual-bottom"\)/);
  assert.match(js, /noteBottomEdge:\s*getComputedStyle\(document\.documentElement\)\.getPropertyValue\("--finance-note-bottom-edge"\)/);
  assert.match(js, /postUiProbe\("visual-probe:entry-note"/);
  assert.match(js, /fullCategoryRowsBeforeNote/);
  assert.match(captureHarness, /fullRowsBeforeNote < 4/);
  assert.match(captureHarness, /note button overlaps camera button/);
  assert.match(captureHarness, /function measureEntryNoteFocusLayout/);
  assert.match(captureHarness, /Entry note focus layout contract failed/);
  assert.match(captureHarness, /note overlay height does not match visual viewport/);
  assert.match(captureHarness, /note focus sheet is not pinned near the visual viewport bottom/);
  assert.match(js, /rects:\s*{/);
  assert.match(js, /currentCategory:\s*rect\("\.finance-entry-category-current"\)/);
  assert.match(js, /cameraButton:\s*rect\("\.wacai-camera-button"\)/);
  assert.match(js, /noteButton:\s*rect\("\[data-entry-note-label\]"\)/);
  assert.match(js, /keyboardComposer:\s*rect\("\[data-finance-keyboard-composer\]"\)/);
  assert.match(js, /keyboardComposerInput:\s*rect\("\[data-finance-keyboard-composer-input\]"\)/);
  assert.match(js, /\.wacai-entry-meta input, \.wacai-entry-meta select, \.wacai-entry-meta button/);
  assert.match(js, /top: roundRectValue\(r\.top\), bottom: roundRectValue\(r\.bottom\), height: roundRectValue\(r\.height\)/);
  assert.match(js, /\.filter\(\(item\) => item\.height > 1\)/);
  assert.match(js, /keypad:\s*rect\("\.wacai-keypad"\)/);
  assert.match(js, /serviceWorker:\s*"finance-mcp-pwa-v148"/);
  assert.match(js, /lastKeypadHandledAt:\s*0/);
  assert.match(js, /lastKeypadHandledKey:\s*""/);
  assert.match(js, /lastKeypadHandledType:\s*""/);
  assert.match(js, /duplicateWindowMs = eventType === "click" \? 500 : 80/);
  assert.match(js, /event\.preventDefault\?\.\(\)/);
  assert.match(js, /\.wacai-keypad"\)\?\.addEventListener\("pointerup", handleKeypad\)/);
  assert.match(js, /\.wacai-keypad"\)\?\.addEventListener\("touchend", handleKeypad, \{ passive: false \}\)/);
  assert.match(captureHarness, /camera button is not pinned near the right edge/);
  assert.match(captureHarness, /meta control height mismatch/);
});

test("light theme does not leave dark chrome on top or bottom bars", () => {
  const html = fs.readFileSync(path.join(root, "public", "finance.html"), "utf8");
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  const css = fs.readFileSync(path.join(root, "public", "styles.css"), "utf8");
  const manifest = JSON.parse(fs.readFileSync(path.join(root, "public", "manifest.json"), "utf8"));
  const webManifest = JSON.parse(fs.readFileSync(path.join(root, "public", "manifest.webmanifest"), "utf8"));

  assert.match(html, /<meta name="theme-color" content="#000000">/);
  assert.match(html, /<style id="finance-anti-flash">/);
  assert.match(html, /html,[\s\S]*body\s*{[\s\S]*background:\s*#000000/);
  assert.match(html, /:root\[data-theme="light"\],[\s\S]*:root\[data-theme="light"\] body\s*{[\s\S]*background:\s*#f2f2f5/);
  assert.match(html, /@media \(prefers-color-scheme:\s*light\)[\s\S]*:root\[data-theme="system"\]/);
  assert.match(html, /window\.__FINANCE_PLUGIN_APPEARANCE__/);
  assert.match(html, /document\.documentElement\.dataset\.pluginFontSize = fontSize/);
  assert.match(html, /localStorage\.getItem\("financePluginFontSize"\) \|\| "normal"/);
  assert.match(js, /metaTheme\.setAttribute\("content", effectiveLight \? "#f2f2f5" : "#000000"\)/);
  assert.match(js, /const HOST_APPEARANCE = window\.__FINANCE_PLUGIN_APPEARANCE__ \|\| \{\}/);
  assert.match(js, /function applyPluginFontSize\(size\)/);
  assert.match(js, /document\.documentElement\.dataset\.pluginFontSize = value/);
  assert.match(js, /function initialTheme\(\)/);
  assert.match(js, /function initialPluginFontSize\(\)/);
  assert.match(css, /:root\[data-theme="light"\]\s*{[\s\S]*--chrome-bg:\s*rgba\(255,\s*255,\s*255,\s*0\.96\)/);
  assert.match(css, /:root\[data-plugin-font-size="compact"\]\s*{[\s\S]*--finance-font-scale:\s*0\.94/);
  assert.match(css, /:root\[data-plugin-font-size="large"\]\s*{[\s\S]*--finance-font-scale:\s*1\.08/);
  assert.match(css, /body\s*{[\s\S]*font-size:\s*calc\(14px \* var\(--finance-font-scale\)\)/);
  assert.match(css, /:root\[data-theme="light"\]\s*{[\s\S]*--nav-bg:\s*#ffffff/);
  assert.doesNotMatch(css, /\.finance-topbar\s*{[\s\S]*background:\s*rgba\(0,\s*0,\s*0,\s*0\.92\)/);
  assert.doesNotMatch(css, /\.finance-bottom-nav\s*{[\s\S]*background:\s*#1b1b1d/);
  assert.equal(manifest.theme_color, "#000000");
  assert.equal(webManifest.theme_color, "#000000");
  assert.equal(manifest.background_color, "#000000");
  assert.equal(webManifest.background_color, "#000000");
});

test("finance UI supports Hermes embedded-app iframe contract", () => {
  const html = fs.readFileSync(path.join(root, "public", "finance.html"), "utf8");
  const js = fs.readFileSync(path.join(root, "public", "app-finance-ui.js"), "utf8");
  const css = fs.readFileSync(path.join(root, "public", "styles.css"), "utf8");

  assert.match(js, /embed"\)\s*===\s*"hermes"/);
  assert.match(js, /const ROOT_VIEW = "home"/);
  assert.doesNotMatch(html, /data-view="overview"|data-embed-month-expense|finance-embed-overview/);
  assert.match(html, /class="finance-bottom-nav"/);
  assert.match(html, /data-nav-view="entry"/);
  assert.match(html, /data-nav-view="reports"/);
  assert.match(js, /finance\.plugin\.navigation/);
  assert.match(js, /hermes\.plugin\.back/);
  assert.match(js, /finance\.plugin\.back_result/);
  assert.match(js, /finance\.plugin\.refresh_required/);
  assert.match(js, /window\.parent\.postMessage/);
  assert.match(js, /function postBackState\(handled\)/);
  assert.match(js, /postHermesBackResult\(handled\);[\s\S]*postHermesNavigation\(\);/);
  assert.match(js, /\.finance-swipe-row\.actions-open/);
  assert.match(js, /window\.addEventListener\("message", handleHermesMessage\)/);
  assert.match(js, /sanitizeRoute/);
  assert.match(js, /function isBackableView\(view = state\.activeView\)/);
  assert.match(js, /return Boolean\(view && view !== ROOT_VIEW\)/);
  assert.match(js, /canGoBack:\s*currentCanGoBack\(\)/);
  assert.match(js, /function shouldCaptureEdgeBack\(\)/);
  assert.match(js, /return currentCanGoBack\(\) \|\| IS_HERMES_EMBED;/);
  assert.match(js, /if \(state\.activeView !== ROOT_VIEW\) \{[\s\S]*setView\(ROOT_VIEW\);[\s\S]*return true;[\s\S]*\}/);
  assert.match(js, /touchmove/);
  assert.match(js, /event\.preventDefault\(\);[\s\S]*goBack\(\)/);
  assert.match(js, /if \(IS_HERMES_EMBED\) postBackState\(handled\);/);
  assert.match(js, /refreshNoticeAt/);
  assert.match(js, /requestHermesRefresh\("static_assets_changed"\)/);
  assert.equal(/rawContent|document\.cookie/.test(js), false);
  assert.doesNotMatch(css, /finance-embed-shortcuts|finance-embed-overview|data-finance-view="overview"/);
  assert.match(html, /data-theme="dark"/);
});

test("finance UI exposes installable PWA metadata", () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(root, "public", "manifest.json"), "utf8"));
  const webManifest = JSON.parse(fs.readFileSync(path.join(root, "public", "manifest.webmanifest"), "utf8"));
  const serviceWorker = fs.readFileSync(path.join(root, "public", "service-worker.js"), "utf8");
  const icon = fs.readFileSync(path.join(root, "public", "icons", "finance-icon.svg"), "utf8");

  assert.equal(manifest.name, "Finance MCP");
  assert.equal(manifest.start_url, "/finance.html?source=pwa");
  assert.equal(manifest.scope, "/");
  assert.equal(manifest.display, "standalone");
  assert.deepEqual(manifest.display_override, ["standalone", "minimal-ui", "browser"]);
  assert.deepEqual(manifest.launch_handler.client_mode, ["focus-existing", "navigate-existing", "auto"]);
  assert.equal(webManifest.display_override[0], "standalone");
  assert.ok(manifest.icons.some((item) => item.src === "/icons/finance-icon-192.png" && item.sizes === "192x192" && item.type === "image/png"));
  assert.ok(manifest.icons.some((item) => item.src === "/icons/finance-icon-512.png" && item.sizes === "512x512" && item.type === "image/png"));
  assert.ok(manifest.icons.some((item) => item.src === "/icons/finance-icon.svg" && /maskable/.test(item.purpose)));
  assert.match(serviceWorker, /CACHE_NAME/);
  assert.match(serviceWorker, /finance\.html/);
  assert.match(serviceWorker, /manifest\.json/);
  assert.match(serviceWorker, /finance-icon-192\.png/);
  assert.match(serviceWorker, /finance-icon-512\.png/);
  assert.match(serviceWorker, /startsWith\("\/api\/"\)/);
  assert.match(icon, /viewBox="0 0 512 512"/);
});
